name: Build and Add APK to Git

on:
  push:
    branches:
      - master

jobs:
  build_and_add:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v1

    - name: Update package name
      run: |
        sed -i 's/com.example.examplepackagechange/com.cts.ar.demo/' android/app/build.gradle
        sed -i 's/example.examplepackagechange/cts.ar.demo/' pubspec.yaml

    - name: Build APK
      run: flutter build apk --release

    - name: Add APK to Git
      uses: EndBug/add-and-commit@v4
      with:
        message: "Add APK file"
        add: |
          build/app/outputs/flutter-apk/app-release.apk
